remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Derrick Ryan Art & Animation
description: > # this means to ignore newlines until "baseurl:"
  Computer Animation and Artwork Demos by Derrick Ryan
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.derrickryanartanimation.com/" # the base hostname & protocol for your site
github_username:  DeranReizer
linkedin_username: dryan-animations
year_range: 2020-2023

